### PR TITLE
Rebuild/Linting

### PR DESCRIPTION
**Pull request by brettz9**
- Build: Rebuild against latest devDeps
- Refactoring: Avoid useless declaration
- Linting: Add `lgtm.yml` to avoid `dist` errors showing up at https://lgtm.com/projects/g/naver/image-maps/alerts/?mode=list

My apologies, I realized I had one more minor PR to submit.

### CODE REVIEW

**Comment by brettz9** [comment]
Great, thanks for the pull! I saw you added a 1.0.1 tag... Did you mean to `npm publish`?

**Comment by brettz9** [comment]
Though I guess `package.json` hasn't been bumped yet...

**Comment by ahnbj2000** [comment]
I just ran npm publish after modifying the tag.

**Comment by brettz9** [comment]
Excellent, thanks very much!

**Pull request merged**
